// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.2
// source: WeatherAPI.proto

package Weather

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WeatherRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *WeatherRequest) Reset() {
	*x = WeatherRequest{}
	mi := &file_WeatherAPI_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeatherRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeatherRequest) ProtoMessage() {}

func (x *WeatherRequest) ProtoReflect() protoreflect.Message {
	mi := &file_WeatherAPI_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeatherRequest.ProtoReflect.Descriptor instead.
func (*WeatherRequest) Descriptor() ([]byte, []int) {
	return file_WeatherAPI_proto_rawDescGZIP(), []int{0}
}

type WeatherReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Temperature int64 `protobuf:"varint,1,opt,name=temperature,proto3" json:"temperature,omitempty"`
	Humidity    int64 `protobuf:"varint,2,opt,name=humidity,proto3" json:"humidity,omitempty"`
	Cloudy      bool  `protobuf:"varint,3,opt,name=cloudy,proto3" json:"cloudy,omitempty"`
}

func (x *WeatherReply) Reset() {
	*x = WeatherReply{}
	mi := &file_WeatherAPI_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeatherReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeatherReply) ProtoMessage() {}

func (x *WeatherReply) ProtoReflect() protoreflect.Message {
	mi := &file_WeatherAPI_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeatherReply.ProtoReflect.Descriptor instead.
func (*WeatherReply) Descriptor() ([]byte, []int) {
	return file_WeatherAPI_proto_rawDescGZIP(), []int{1}
}

func (x *WeatherReply) GetTemperature() int64 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *WeatherReply) GetHumidity() int64 {
	if x != nil {
		return x.Humidity
	}
	return 0
}

func (x *WeatherReply) GetCloudy() bool {
	if x != nil {
		return x.Cloudy
	}
	return false
}

var File_WeatherAPI_proto protoreflect.FileDescriptor

var file_WeatherAPI_proto_rawDesc = []byte{
	0x0a, 0x10, 0x57, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x41, 0x50, 0x49, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x10, 0x0a, 0x0e, 0x57, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x64, 0x0a, 0x0c, 0x57, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x65, 0x6d, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x75, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x74, 0x65, 0x6d, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x75, 0x6d, 0x69, 0x64, 0x69,
	0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x68, 0x75, 0x6d, 0x69, 0x64, 0x69,
	0x74, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x79, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x06, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x79, 0x32, 0x47, 0x0a, 0x0f, 0x57, 0x65,
	0x61, 0x74, 0x68, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x12, 0x34, 0x0a,
	0x10, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x64, 0x61, 0x79, 0x73, 0x57, 0x65, 0x61, 0x74, 0x68, 0x65,
	0x72, 0x12, 0x0f, 0x2e, 0x57, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x57, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x00, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2f, 0x57, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_WeatherAPI_proto_rawDescOnce sync.Once
	file_WeatherAPI_proto_rawDescData = file_WeatherAPI_proto_rawDesc
)

func file_WeatherAPI_proto_rawDescGZIP() []byte {
	file_WeatherAPI_proto_rawDescOnce.Do(func() {
		file_WeatherAPI_proto_rawDescData = protoimpl.X.CompressGZIP(file_WeatherAPI_proto_rawDescData)
	})
	return file_WeatherAPI_proto_rawDescData
}

var file_WeatherAPI_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_WeatherAPI_proto_goTypes = []any{
	(*WeatherRequest)(nil), // 0: WeatherRequest
	(*WeatherReply)(nil),   // 1: WeatherReply
}
var file_WeatherAPI_proto_depIdxs = []int32{
	0, // 0: WeatherReporter.GetTodaysWeather:input_type -> WeatherRequest
	1, // 1: WeatherReporter.GetTodaysWeather:output_type -> WeatherReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_WeatherAPI_proto_init() }
func file_WeatherAPI_proto_init() {
	if File_WeatherAPI_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_WeatherAPI_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_WeatherAPI_proto_goTypes,
		DependencyIndexes: file_WeatherAPI_proto_depIdxs,
		MessageInfos:      file_WeatherAPI_proto_msgTypes,
	}.Build()
	File_WeatherAPI_proto = out.File
	file_WeatherAPI_proto_rawDesc = nil
	file_WeatherAPI_proto_goTypes = nil
	file_WeatherAPI_proto_depIdxs = nil
}
